spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        healthCheckInterval: 10s
        healthCheckUrl: http://localhost:8502/health
        hostname: localhost
        instance-id: consul-miya
        service-name: consul-miya
        port: 8502
        tags: dev
  application:
    name: consul-miya
server:
  port: 8502
