server:
  port: 8760
spring:
  profiles: peer1
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/